spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
  thymeleaf:
    cache: false

server:
  port: 8081
