spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres #Нужно указать вашу БД
    username: postgres # пользователь который указат у вас при создании БД
    password: postgres # пароль который указат у вас при создании БД
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update

server:
  port: 8081
